# Site
name: "Neokorteks"
title: "Neokorteks Dergisi"
description: "Bilinçli Bilim"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'neokorteks'
mailchimp-list: 'https://neokorteks.us1.list-manage.com/subscribe/post?u=cb622d3a17b83089851f6080e&amp;id=7c74fb42b9'
include: ["_pages"]
permalink: /:title/
email: bilgi@neokorteks.tk

# Authors
authors:
  efe:
    name: Efe Kaan Altaş
    display_name: Efe Kaan Altaş
    avatar: 'assets/images/efe.jpg'
    email: efekaanaltas@yandex.com.tr
    description: "Neokorteks yazarı, oyun geliştiricisi ve Türkiye Kareli Gömlek Giyenler Federasyonu Başkanı."
  arda:
    name: Arda Cengiz
    display_name: Arda Cengiz
    avatar: 'assets/images/arda.jpg'
    email: cengizarda2005@gmail.com
    twitter: https://twitter.com/Arda_cngz
    description: "Neokorteks'te araştırmacı, bilim meraklısı ve dil bilimci."
  zeynepyaman:
    name: Zeynep Yaman
    display_name: Zeynep Yaman
    avatar: 'assets/images/zyaman.jpg'
    email: zeynepyaman7788@gmail.com 
    twitter: https://twitter.com/Zeyneppyamnn
    description: "Fantastik roman okuyucusu. Hayali Koç Üniversite’sinde Moleküler Biyoloji ve Genetik Mühendisliği okumak."
  asude:
    name: Asude Kandazoğlu
    display_name: Asude Kandazoğlu
    avatar: 'assets/images/akandazoglu.jpg'
    email: asdkndzgl@gmail.com
    description: "Coğrafyaya, fiziğe ve felsefeye ilgili. Boş zamanlarında resim yapıyor."
  nermininan:
    name: Nermin İnan
    display_name: Nermin İnan
    avatar: 'assets/images/ninan.jpg'
    email: nermin_inan@hotmail.com
    twitter: https://twitter.com/nermin_inan
    description: "Biyoloji öğretmeni. Neokorteks'in fikir babası."
  berkeakyel:
    name: Berke Akyel
    display_name: Berke Akyel
    avatar: 'assets/images/baykel.jpg'
    email: berkeakyel191@gmail.com
    twitter: https://twitter.com/AkyelBerke05
    description: "Psikolojiye düşkün. Kitap okumayı sever. Hemen hemen her alana meraklı..."
  nisaturgut:
    name: Nisa Turgut
    display_name: Nisa Turgut
    avatar: 'assets/images/nturgut.jpg'
    email: nisaturgut43@gmail.com
    twitter: https://twitter.com/nisaa_turgut
    description: " "
  tahabiyikli:
    name: Talip Taha Bıyıklı
    display_name: Talip Taha Bıyıklı
    avatar: 'assets/images/avatar.png'
    email: taliptaha06@gmail.com
    twitter: https://twitter.com/tahabykl
    description: "güvenlik araştırmacısı"
  egegenc:
    name: Ege Genç
    display_name: Ege Genç
    avatar: 'assets/images/avatar.png'
    email: gencege5506@gmail.com
    twitter: https://twitter.com/egegencc
    description: "Neokorteks Yazarı."
  sevvalbulut:
    name: Şevval Deniz Bulut
    display_name: Şevval Deniz Bulut
    avatar: 'assets/images/avatar.png'
    email: sevvaldenizbulut@gmail.com
    description: "Neokorteks'te yazar; uzay, kuantum fiziği ve biyolojiye ilgili."
  mehlikacakir:
    name: Mehlika İclal Çakır
    display_name: Mehlika İclal Çakır
    avatar: 'assets/images/avatar.png'
    email: mehlikaiclal52@gmail.com
    description: " "
  pinarertan:
    name: Pınar Ertan
    display_name: Pınar Ertan
    avatar: 'assets/images/avatar.png'
    email: Ertanpinar500@gmail.com
    description: "Neokorteks dergisi yazarı, bilime meraklı bir öğrenci."
  caglagunduz:
    name: Çağla Gündüz
    display_name: Çağla Gündüz
    avatar: 'assets/images/avatar.png'
    email: musicmusic2855@gmail.com
    description: "Müzik ve keman tutkunu. Kitap okumayı sever. Bilimsel araştırma meraklısı ve Neokorteks Dergisi yazarı."
  cicekguzel:
    name: Çiçek Güzel
    display_name: Çiçek Güzel
    avatar: 'assets/images/avatar.png'
    email: cicekgz625@gmail.com
    description: "Genetikle ilgili, Neokorteks'te araştırmacı"
  ekin:
    name: Ekin Şiar Bayer
    display_name: Ekin Şiar Bayer
    avatar: 'assets/images/avatar.png'
    email: ekinsiarb@protonmail.com
    twitter: http://twitter.com/EkinBayer4
    description: "Siber güvenlik araştırmacısı, sporcu ve bilgisayar bilimleri ile ilgileniyor."
  tubag:
    name: Tuba Bağ
    display_name: Tuba Bağ
    avatar: 'assets/images/avatar.png'
    email: tubag55@outlook.com
    twitter: https://twitter.com/tubag00
    description: "Psikoloji ve bilime ilgili. Boş zamanlarını resim puzzle yapma gibi aktivitelerle geçiriyor."
  kaansecgin:
    name: Kaan SEÇGİN
    display_name: Kaan SEÇGİN
    avatar: 'assets/images/avatar.png'
    email: kaansecgin785@gmail.com
    description: "Samsun'un Çarşamba ilçesinde yaşıyor."
  sati:
    name: Satı Melike ŞİŞLİ 
    display_name: Satı Melike ŞİŞLİ 
    avatar: 'assets/images/avatar.png'
    email: satimelikesisli@gmail.com 
    description: "Neokorteks dergisinde yazı yazıyor. Psikoloji bilimine ilgili."
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
