# Site
name: "Neokorteks"
title: "Neokorteks Dergisi"
description: "Bilinçli Bilim"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'neokorteks'
mailchimp-list: 'https://neokorteks.us1.list-manage.com/subscribe/post?u=cb622d3a17b83089851f6080e&amp;id=7c74fb42b9'
include: ["_pages"]
permalink: /:title/
email: bilgi@neokorteks.tk

# Authors
authors:
  efe:
    name: Efe Kaan Altaş
    display_name: Efe Kaan Altaş
    avatar: 'assets/images/efe.jpg'
    email: efekaanaltas@yandex.com.tr
    description: "Neokorteks yazarı, oyun geliştiricisi ve Türkiye Kareli Gömlek Giyenler Federasyonu Başkanı."
  arda:
    name: Arda Cengiz
    display_name: Arda Cengiz
    avatar: 'assets/images/arda.jpg'
    email: cengizarda2005@gmail.com
    twitter: https://twitter.com/Arda_cngz
    description: "Neokorteks'te araştırmacı, bilim meraklısı ve dil bilimci."
  zeynepyaman:
    name: Zeynep Yaman
    display_name: Zeynep Yaman
    avatar: 'assets/images/zeynepyaman.jpg'
    email: zeynepyaman7788@gmail.com 
    twitter: https://twitter.com/Zeyneppyamnn
    description: "Fantastik roman okuyucusu. Hayali Koç Üniversite’sinde Moleküler Biyoloji ve Genetik Mühendisliği okumak."
  asude:
    name: Asude Kandazoğlu
    display_name: Asude Kandazoğlu
    avatar: 'assets/images/asudekandazoglu.jpg'
    email: asdkndzgl@gmail.com
    twitter: https://twitter.com/Zeyneppyamnn
    description: "Coğrafyaya, fiziğe ve felsefeye ilgili. Boş zamanlarında resim yapıyor."
  nermininan:
    name: Nermin İnan
    display_name: Nermin İnan
    avatar: 'assets/images/nermininan.png'
    email: nermin_inan@hotmail.com
    description: "Biyoloji öğretmeni. Neokorteks'in fikir babası."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
